test new change

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -71,12 +71,19 @@ jobs:
           
           
           # Comment on each issue found
+          FAILURES=""
+          
           echo "$ISSUE_NUMBERS" | tr ' ' '\n' | while read -r issue_number; do
             if [ -n "$issue_number" ]; then
               echo "Commenting on issue #$issue_number"
-              if ! gh issue comment "$issue_number" --body "A change related to this issue was included in release: $CURRENT_TAG"; then
+              if ! gh issue comment "$issue_number" --body "A change related to this issue was included in [release **$CURRENT_TAG**](https://github.com/${{ github.repository }}/releases/tag/$CURRENT_TAG)."; then
                 echo "::error::Failed to comment on issue #$issue_number"
-                exit 1
+                FAILURES="$FAILURES #$issuenumber"
               fi
             fi
           done
+          
+          if [ -n "$FAILURES" ]; then
+            echo "::error::Failed to update the following issue(s):$FAILURES"
+            exit 1
+          fi
